---
- name: Download Java
  command: "wget --no-check-certificate https://download.oracle.com/otn-pub/java/jdk/8u192-b12/750e1c8617c5452694857ad95c3ee230/jdk-8u192-linux-x64.tar.gz && dpkg -i jdk-8u192-linux-x64.tar.gz"
